nuprl/website

blog/_src/posts/2016-10-11-compcert-overview.md
A little advert for my notes on CompCert from Amal's topics class.
(Thanks @gasche  for suggesting we blogpost this)
Here's a preview:
http://www.ccs.neu.edu/home/types/nuprl.github.io/ccomp.html
=> [blog] compcert overview

blog/_src/posts/2016-11-29-getting-started-in-programming-languages.md, blog/_src/posts/2016-11-30-getting-started-in-programming-languages-cross-post.md
I'd like to start cross-posting some of the posts from my personal blog on the PRL blog. This PR just adds a post that links to my own blog, but I'd like to get feedback on how others think cross-posting to the lab blog should work.
=> Add Getting Started in PL post

publications.rkt
I just added my SNAPL paper.
The two still missing publications from the group that I know of are:
- the ESOP'17 paper by Ryan and @cobbal 
- the SNAPL'17 paper by @mfelleisen and others
=> update 'Publications' page

blog/_src/posts/2017-04-19-prl-at-snapl-17.md, blog/_src/posts/2017-04-25-prl-at-snapl-17.md
I don't currently have an URL for the Migratory Types paper, so there is no link pointing to it in the post. If we can get a publicly-accessible URL in the following few days, I would suggest to wait until we have one to publish the post.
(I wondered about the snarky remarks on SNAPL at the end but, oh well, this is an occasion to give feedback.)
=> blog post: three SNAPL'17 PRL papers

deploy.sh
@gasche @bennn 
Here's the quick fix I suggested. See the commit for description, but it matches our email thread.
I have _not_ tested this on Travis -- it's somewhat of a pain to test (I did test the shell conditional syntax locally), so as long as it looks good to y'all, we should just push it and if it doesn't work I'll fix it (i.e., test it live!).
I looked into submitting the issue if things go wrong, but it didn't look trivial (there is a gem `ghi` that allows you to do this, but you need to authenticate, and it doesn't seem like it'll use the same `.netrc` that we use for authenticating with git).
=> Add fix to make races when deploying much less likely.

.travis.yml, blog/_src/posts/2017-05-23-scribble-html.md
On my machine syntax highlighting works, and according to [this frog documentation page](https://github.com/greghendershott/frog/blob/master/example/_src/posts/2012-01-01-a-2012-blog-post.md) it is because I have Pygments installed. So I tried to make the Travis CI install Pygments when it builds the website, but I have no way to test besides sending a PR, so there it is. (And then I don't know if we can check whether highlighting actually works without merging it.)
=> Syntax highlighting

blog/_src/posts/2017-06-05-syntactic-parametricity-strikes-again.md
@gasche  
Here's the abstract before this PR:
And here it is after:
=> [blog] move mathjax definitions, removes extra whitespace

blog/_src/posts/2018-10-05-defining-local-bindings-in-turnstile-languages.md, blog/_src/posts/2018-10-22-defining-local-bindings-in-turnstile-languages.md
One thing I noticed is the formatting of the numeral `1` in code blocks is awful, I'm pretty sure it's white on a gray background, but I'm not sure how to fix it.
=> blog post on creating define-like binding forms in Turnstile

publications.rkt
[pubs page manager hat on] This change was proposed by @janvitek, I support it. 
*Discussion*
Long and diverse URLs are ugly. The only downside I see: with the current font size settings the `[link]` link is a bit hard to target. I would argue for enlargement of the font size site-wide: it seems that the current size was chosen in the era of 640x480. That should go as a separate PR, of course.
=> Print just "link" instead of URL for papers on Pubs page

README.md, css/custom.css, seminars.rkt
This took longer than expected, because my Racket-fu is weak and my Scribble-fu is weaker. Comments are welcome.
Before merging, let me know so I can set up the [cron job](https://docs.travis-ci.com/user/cron-jobs/).
CSS fix (note that this is an upcoming seminar), before and after:
Commit message below:
```
Upcoming seminars show up first, in chronological order, so the next
seminar is first. Afterwards, past seminars are displayed in reverse
chronological order, so the most recent seminar is first. For example:
- NEXT SEMINAR
- NEAR FUTURE
- FAR FUTURE
- most recent seminar
- near past
- far past
This required a few other changes, such as defining a `seminar` struct
to defer the Scribble rendering until after the partition and sorting.
Note that the sorting is done in the build step, so …
```
=> Improve the order of seminars

blog/_src/posts/2018-12-02-java-transient.md
This post argues that Java is a migratory typing system, and shows how it is pretty similar to the transient idea for Reticulated Python.
I couldn't find details online about how `javac` inserts casts, so that's missing from the post.
Any other suggestions about technical content to add would be welcome
=> blog: Java and migratory typing

css/custom.css, seminars.rkt
Add two new headings to the seminars page to explain the new organization (#175)
Picture of 1st new heading:
Picture of 2nd new heading:
Should the labels say "Future Seminars" / "Past Seminars" instead? Something else?
=> add 'Upcoming Seminars' and 'Past Seminars' headings

install-racket.sh
This is a stop-gap measure already applied on the racket-lang.org, while folks are figuring out the state of mirror.racket-lang.org.
=> deployment script: switch to Utah server for now, while Boston server is down

.travis.yml
The build of #203 failed ([travis link](https://travis-ci.org/nuprl/website/builds/573962123?utm_source=github_status&utm_medium=notification), [full log](https://github.com/nuprl/website/files/3521191/nuprl-website-913.txt)). I think this PR will fix it.
Sources:
- https://stackoverflow.com/questions/55674746/travis-sh-0-cant-open-etc-init-d-xvfb
- https://benlimmer.com/2019/01/14/travis-ci-xvfb/
- https://docs.travis-ci.com/user/gui-and-headless-browsers/#using-xvfb-to-run-tests-that-require-a-gui
=> use xvfb 'service' in travis script

blog/_src/posts/2019-09-05-lexical-and-dynamic-scope.md
This is the first of two blog posts that supersedes #202.
I decided to focus only on the definitions of lexical/dynamic scope, deferring all the R stuff to a later post. As a result, I significantly rewrote the definitions of lexical/dynamic scope, added some opinion about why I think it's so hard to get right, and then wrote a short timeline of lexical scope in ALGOL, Lisp, and Scheme.
For convenience, you can find a rendered version [here](http://www.ccs.neu.edu/home/mhyee/scratch/Lexical%20and%20Dynamic%20Scope.html?2).
I'll have a draft/PR for part two up soon. I'd like to get both posts published within days of each other, preferably before Wednesday next week.
=> [blog] Lexical and dynamic scope

index.rkt, new-members.rkt, templates.rkt
I noticed that if you go to https://prl.ccs.neu.edu instead of http://prl.ccs.neu.edu, the fonts are broken. This is because fonts are loaded over http, not https.
I also updated a few old links. (*.neu.edu redirects to *.northeastern.edu and forces https.)
Question: do we want to [enforce https](https://help.github.com/articles/securing-your-github-pages-site-with-https/)? If we do, then I think we break #43 because our analytics sends requests over http.
=> Update some links

css/pygments.css
Fixes #224
- for code blocks this revert the style to the default state (before it was changed by #85)
- for math the new definition has the same output as after #85, that is, not-completely-horrible
The fix was suggested by Ben in
https://github.com/nuprl/website/issues/224#issuecomment-534272207
It could be reasonable to qualify *all* CSS settings of this file to code blocks. I only went for the fix of minimal invasiveness (in terms of diff in this PR, or diff with respect to the pre-#85 state).
=> fix number formatting in code blocks

blog/_src/post-template.html
Because Google is killing Google+
Closes #150
=> blog: remove 'Google Plus share' button

seminars.rkt
The website's seminar listing is out-of-date, and this PR lists the missing seminars from the past few months (Zoe Paraskevopoulou, Ralf Jung, and Ross Tate). I have also commented out the entry for Yuriy Brun's seminar, since that was postponed into the next year.
In the future, I'm happy to push seminar changes directly to master (if given access) or to continue using pull requests :-)
=> Update seminar webpage

new-members.rkt
- Add a link to the Slack channel (not an invite link)
- Remove the 404 housing map & the outdated links to housing sites
- CCIS -> Khoury
---
Questions:
1. Is there a Slack invite link that we can post?
2. Can anyone find useful housing links? I'm sorry to lose this info, even though it wasn't much. But I don't know where the Google map went, the `jefftk` rent map looks useless, and the Trulia link doesn't point to a map.
=> new-members: +slack, -housing

blog/_src/post-template.html
This addresses #98 by adding optional comments powered by Disqus. The comments (and corresponding JS code of Disqus) are not loaded unless the user explicitly asks so.
Previews (click to expand):
<details>
<summary>Screnshot: comments have not been loaded yet (the default)</summary>
</details>
<details>
<summary>Screnshot: comments have been loaded after the client clicked "Show comments" (see the previous screenshot)</summary>
</details>
=> Blog: add Disqus comments loaded on-demand if client explicitly asks

blog/_src/posts/2020-10-15-shallow-mailing-list.md
Blog post showing what transient (Shallow Typed Racket) does on a few example programs from the Racket mailing list. Spoiler: transient always does the right thing.
I'm planning to merge this tomorrow afternoon (2pm?) because I need to reference it for RacketCon this weekend.
(If you happen to comment after the merge, I'll update the post.)
=> blog: transient examples

contact.rkt, new-members.rkt, people.rkt
Addresses #280. I also removed references to husky emails since those are deprecated now (@aviralg and @olekgierczak holler if you prefer a different email).
=> Update contact page and remove husky addresses

.github/workflows/build.yml
After the [latest update][u] of the setup-racket action (v1.7), caching works correctly with packages, so updating the action and putting caching back.
[u]: https://github.com/Bogdanp/setup-racket/releases/tag/v1.7
=> GHA: update setup-racket action, return caching

templates.rkt
The page requests two HTML5 polyfills.   These are supposed to be conditional on IE < 9, but a typo makes them unconditional.   This usually doesn't matter much, but the CDN we were referencing no longer serves them at that URI.   So this updates the URI and makes them conditional.   I checked that most pages render reasonably in current Firefox and current Chromium with this change, but **did not test in Internet Explorer**.    If someone wants to check it, be my guest, but i'm not worried about it if no one else is.
=> Don't load IE resources on other browsers; update URIs

css/custom.css, publications.rkt
It's still quite wide on wide screens, but this follows the convention seemingly followed by the rest of the site
=> Wrap publications like other main content (Fixes #327)

publications.rkt
* Added remaining papers for 2023
* Added papers for early 2024
=> Updated Publications Page

publications.rkt
=> add more camoy pubs
