nuprl/website

blog/_src/posts/2016-10-17-emacs-daemon-for-fast-editor-startup.md

This is extracted from a reddit comment:
<https://www.reddit.com/r/haskell/comments/57m199/is_it_worth_to_switch_from_atom_to_emacs/d8t3spl>

new blog post on `emacsclient`

---

blog/_src/posts/2016-10-19-history-of-actors.md

Reasonable post? Anything else I should include? Did I do everything format- and repo-layout-wise right?

Small pointer blog post re History of Actors

---

blog/_src/posts/2016-11-02-beta-reduction-part-1.md

Blog post meant to introduce beta reduction.  Let me know what you think.  The writing/explanation may need work.

Beta blog1

---

publications.rkt

Fixes #20 by both removing publications from when no author was affiliated with the lab and merging all remaining publications into a single list.
Can someone look this over and sanity-check my changes?

Merge publication lists and 

---

blog/_src/page-template.html
blog/_src/posts/2016-11-16-constructive-galois-connections.md

Here's a draft of a blog post I've been meaning to write since before ICFP about David Darais' paper.
Typos and writing feedback appreciated.

Blog Post about Constructive Galois Connections

---

README.md
blog/_src/posts/2016-11-17-src-submissions.md

cc @maxsnew @dbp 
@dbp is super-busy today and tomorrow and probably won't have time to comment, I plan to wait a few extra days to give him an opportunity for feedback. (please don't merge before that)

SRC blog post

---

publications.rkt

New publis

---

blog/_src/page-template.html
blog/_src/posts/2016-11-17-src-submissions.md

fix #30  (using an inline style property 🙁 )
and change my name to "Ben" in the SRC post

blog title link

---

blog/_src/posts/2016-12-17-measuring-the-submission-review-balance.md

Written for (some kind of) fun. What do you think?

Measuring the submission/review balance

---

people.rkt

- Move after Dan's entry
- Change email address
- Shorten description

Minor edits to mhyee on People page

---

blog/_src/posts/2017-01-02-fall-2016-pl-junior-retrospective.md

did we ever figure anything out w.r.t multiple authors? @mhyee @BenChung @MiloDavis and myself wrote this.

blog post on fall 2016 pl junior

---

blog/_src/posts/2017-02-21-bullets-are-good-for-your-coq-proofs.md

new blog post: Bullets are good for your coq proofs

---

people.rkt

* Uses personal domain for website pointer
* Updates current affliation

Updating profile for sstrickl

---

blog/_src/posts/2017-02-28-pliss-oregon-without-the-greek.md

new blog post: PLISS, Oregon without the greek (by Jan)

---

blog/_src/posts/2017-03-10-tracing-jits-for-dynamic-languages.md
blog/_src/posts/2017-03-15-tracing-jits-for-dynamic-languages.md

Not quite finished.
I'm still typesetting my lecture notes, and it'll probably take a few more days. But @bennn asked me to prepare a blog post for now.
It seems a bit silly to publish this if **both** the discussion notes and lecture notes are missing. I'd rather wait until the lecture notes are done, but in the meantime, it's probably better to merge the discussion notes (https://github.com/nuprl/hopl-s2017/pull/7) (and maybe commit @gasche's version as well). I can update the blog post later, when the lecture notes are done.
Thoughts?

[blog][hopl] Tracing JITs

---

blog/_src/posts/2017-04-17-hopl-types-in-compilation.md

@LeifAndersen @wilbowma 
Planning to merge this tomorrow morning. Let me know if you want to make any changes.

[blog] HOPL: ad for Leif / William

---

publications.rkt

include the remaining SNAPL'17 paper

---

blog/_src/posts/2017-05-09-hopl-no-good-answers.md

[blog] HOPL, gradual typing

---

blog/_src/posts/2017-05-12-artifacts-for-semantics.md
blog/_src/posts/2017-05-15-artifacts-for-semantics.md

@gasche has been bugging me to write a blog post forever, so here, I present! 
The point of the post is:
1. Explain how we wrote our artifact, as I think it went well and is worth re-using as a strategy.
2. Advocate for building artifacts solely for understanding papers.

[blog] Add blog post about writing funtal artifact

---

blog/_src/page-template.html
templates.rkt

Add a link from each page to this github repo

link to source code

---

blog/_src/posts/2017-06-05-bridging-the-system-configuration-gap.md
blog/_src/posts/2017-06-09-bridging-the-system-configuration-gap.md

cc @gasche 
The post is actually on my blog with this serving as a cross-post link, but I'd appreciate any feedback:
https://aaronweiss.us/posts/2017-06-05-bridging-the-system-configuration-gap.html
You can comment [here](https://github.com/aatxe/aaronweiss.us/commit/6dc4b6df0ee1d686c088b9ff1fad286bbf37e803) if you like inline comments.

[Blog Post] Bridging the System Configuration Gap

---

blog/_src/posts/2017-06-24-turing-award-50.md

notes, quotes, stories from the ACM celebration of the Turing Award

blog: Turing Award 50

---

blog/_src/posts/2017-08-24-closure-conversion-coyoneda.md
blog/_src/posts/2017-08-28-closure-conversion-coyoneda.md

Finally fulfilling my bet to @gasche

Closure conversion = coyoneda blog post

---

blog/_src/posts/2017-09-27-final-algebra-semantics-is-observational-equivalence.md

Blog post based on reading @mwand 's final algebra paper and some discussions with @michaelballantyne and @rmculpepper
A couple things:
1. @michaelballantyne do you want me to link your blog in my post? It looks like you haven't updated it since 2014 and if not do you have a different website to link?
2. The part about adequacy can probably be expanded.

Final algebra Semantics Blog Post

---

blog/_src/posts/2017-09-27-final-algebra-semantics-is-observational-equivalence.md

Fixes some typos in Final Algebra blog post

---

blog/_src/page-template.html

Change from racketlang to neu_prl
Closes https://github.com/nuprl/nuprl.github.io/issues/81

blog: update twitter follow link

---

seminars.rkt

I grabbed this bio from her website -- I'd like to at least have her confirm that it's okay (as Matthias's announcement did not include a bio) before we merge this.

Add chris martens seminar

---

seminars.rkt

@janvitek or @BenChung Do we have a website for Molham? Or Relational AI? Googling both did not turn up anything that looked obviously appropriate.

add seminar for Molham Aref

---

blog/_src/posts/2018-01-17-how-to-prove-a-compiler-correct.md

I wrote a blog post about proving a (very) toy compiler correct, based on a conversation William and I had with a person at POPL. This is a cross-post, but the post on my site is not public yet (insofar as anything can be not public on the internet), so feedback / edits / suggestions are all welcome (from anyone, but particularly curious what @bennn @wilbowma @maxsnew and @gasche if he's still lurking around think). Not planning on posting it anywhere before on the PRL blog. The link, for the lazy, is: https://dbp.io/essays/2018-01-16-how-to-prove-a-compiler-correct.html

blog: add cross-post proving a toy compiler correct

---

blog/_src/posts/2018-04-23-how-to-prove-a-compiler-fully-abstract.md

This is a blog post I wrote that explains, at a relatively high level, both what a fully abstract compiler is and more, how one proves it. 
As always, feedback is welcome :)

blog: add cross post about fully abstract compilation

---

blog/_src/posts/2018-05-08-sampling-gradual-typing-performance.md

Hi,
The goal of this post is to explain the sampling method that Zeina and I used to measure the overhead of gradual typing.
The post should be easy to read and easy to skim. I'm worried it's not easy enough. Comments welcome!
I want to merge this post early next week.
cc @migeed-z

blog: explain the sampling method

---

new-members.rkt

I think this is more accurate wording. But feel free to close if you disagree.

by default husky card is blank

---

contact.rkt

@hyeyoungshin is the new PL Jr organizer.

Update PL Jr organizer

---

people.rkt

Fillip Krikava, Konrad Siek, Paley Li, Heather Miller

People Page | restore former members 

---

contact.rkt
css/custom.css

This tries to address #4. See the pictures there.

rework contacts page: several columns, no ugly narrow paragraphs

---

blog/_src/posts/2018-11-24-disappearing-code.md

Mitch sent me a nice comment that I'd like to add to the blog post.
This "comment section" looks like this when built:
Looks okay?

blog: add comment from Mitch

---

seminars.rkt

Lucas Waye's seminar is being rescheduled and the new date is
tentative. I will make his seminar details visible once we
fix a date.

Seminar | Hide Lucas Waye's 12th December seminar details

---

contact.rkt

Hey, @aatxe! Would you be willing to get the official title?

Aaron is the new organizer of happy hours

---

blog/_src/posts/2018-11-24-scribble-acmart.md
blog/_src/posts/2019-02-17-scribble-acmart.md

This post starts with some example code for a tiny paper written with Scribble, then explains how to configure the paper with a `#lang` (because I think that's the best way to go).
For now, I'd like to post this as-is and be done :)
But maybe instead, this should be 2 posts:
1. code for a tiny paper, examples from larger papers with some discussion
2. paper-as-`#lang`
Anyway, comments on the organization would be very welcome. If nobody comments then I will plan to merge this mid-December.

blog: writing a paper with scribble

---

blog/_src/posts/2019-03-09-pliss-learn-about-pl-implementation-in-a-castle.md

pliss blog post

---

new-members.rkt

Both the instructions for contacting the mailing list administrators and also the instructions for which lists to join were somewhat vague. I've clarified them some.

Clarifying mailing list instructions

---

blog/_src/posts/2019-09-05-lexical-and-dynamic-scope.md
blog/_src/posts/2019-09-10-four-kinds-of-scoping-in-r.md
blog/_src/posts/2019-09-10-scoping-in-r.md

This is the second... and third... parts that supersedes #202. Originally this was just part two, but it got long enough that I split it off to make a "bonus" third part, that I plan to publish at the same time.
Most of the code examples are lifted straight from #202, but I added a few new examples, changed the metaprogramming examples, and significantly overhauled the discussion.
I still need to go back and add forward/backward links, update some of the text, update the dates, and fix up #203 (part one). But I think this draft is ready for feedback.
For convenience, I've rendered [part two](http://www.ccs.neu.edu/home/mhyee/scratch/Scoping%20in%20R.html?3) and [part three](http://www.ccs.neu.edu/home/mhyee/scratch/Four%20Kinds%20of%20Scoping%20in%20R.html?3).
I'd like to get feedback in …

[blog] Scoping in R (second attempt) + Four Kinds of Scoping in R

---

blog/_src/posts/2017-09-25-redex-faq.md

Thanks for writing it up; it's very helpful! This PR fixes a small bug in one of the examples.

Fix an example in Redex FAQ

---

blog/_src/posts/2019-11-17-optimizer-vs-transient.md
blog/_src/posts/2020-01-15-tr-optimizer-vs-transient.md

This post is a written version of my PRL offsite talk. It gives a small example of the 15 optimizations in Typed Racket and explains which are trouble for Transient. ~(Hope to merge by Dec 23)~
EDIT: hope to merge soon after Jan 15
I tried to keep each pass short but clear.
I also tried to explain as little as possible about Transient & standard TR.
Let me know if things are too short!

blog: TR optimizer vs. Transient

---

blog/_src/posts/2020-12-23-deep-and-shallow-types.md

blog: ben g dissertation announcement

---

blog/_src/posts/2018-12-02-java-transient.md
blog/_src/posts/2020-01-15-tr-optimizer-vs-transient.md
blog/_src/posts/2020-10-15-shallow-mailing-list.md
blog/_src/posts/2020-11-12-transient-opt-kw-lambda.md

Blog post about a bug-fixing adventure that did not appear in my dissertation.
I hope the story works as a technical introduction to parts or Typed Racket & Racket.
I'd like to merge this week but publish with the 2020-11-12 date. That way, this post shows up below my dissertation post on the blog.

Blog: adventures with optional and keyword functions

---

people.rkt

hey there! I wanted to update some of my details because they're terribly out of date :)

update `Phillip Mates` details

---

.github/workflows/build.yml

following https://github.com/Bogdanp/setup-racket-cache-example

GH Actions: add caching

---

publications.rkt

Updated publications page

---

blog/_src/posts/2022-01-06-introducing-visr-md.md

Fix visr code example

---

seminars.rkt

add kkallas seminar info

---

blog/_src/posts/2022-02-16-rsh-overview-1.md

Planning to document the Ř jit compiler and this is the first post in
that series.
@mhyee do you know if the utf-8 chars work here?

add blog crosspost

---

blog/_src/posts/2022-01-06-introducing-visr-md.md

The link to visr paper appears incorrect?

fix paper link in visr post (#2)

---

seminars.rkt

udpate kkallas seminar loc; zoom only

---

publications.rkt

* Added new entries to the publications page.
* Updated links for some existing entries

* Updated publications page

---

people.rkt

Jason got in touch and asked if I could update the people page since he's moved to SHU.

Jason has moved

---

.github/workflows/build.yml

Package is called `python3-pygments` in Ubuntu 22.04: https://packages.ubuntu.com/jammy/python3-pygments

Try fixing build

---

people.rkt

Link directly to Minsung's non-Khoury site

---

people.rkt

many thanks to @mhyee and @julbinb :)

update ben and leif's dissertation links

---

blog/_src/posts/2017-09-25-redex-faq.md

typo, redex faq
